# Generated by Django 5.1 on 2024-08-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
