# Generated by Django 5.1 on 2024-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
