# Generated by Django 5.1 on 2024-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='stripe_price_id',
            field=models.CharField(default='price_1PrgiYRwKf16U0fbQapGFf1s', max_length=100),
        ),
    ]
