# Generated by Django 5.1 on 2024-08-22 11:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopitem_item_name_alter_shopitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
