# Generated by Django 5.1 on 2024-08-22 11:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopitem_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
