# Generated by Django 5.1 on 2024-09-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopitem_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='stripe_price_id',
        ),
    ]
