# Generated by Django 5.1 on 2024-09-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_shopitem_stripe_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('delivery_address_line1', models.CharField(max_length=200)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_town', models.CharField(max_length=200)),
                ('delivery_address_postcode', models.CharField(max_length=20)),
                ('delivery_address_county', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_address_country', models.CharField(max_length=100)),
                ('order_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.shopitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_items', to='cart.order')),
            ],
        ),
    ]
