# Generated by Django 5.1 on 2024-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_id',
            field=models.CharField(default=123, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
