# Generated by Django 5.1 on 2024-09-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_stripe_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_checkout_id',
        ),
    ]
