# Generated by Django 5.1 on 2024-09-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_stripe_checkout_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address_country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address_county',
            new_name='shipping_county_or_state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address_line1',
            new_name='shipping_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address_line2',
            new_name='shipping_line2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address_postcode',
            new_name='shipping_postal_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address_town',
            new_name='shipping_town_or_city',
        ),
    ]
