# Generated by Django 5.1 on 2024-09-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_delivery_address_country_order_shipping_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_town_or_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
